"""Shared closed-loop status contract for RRKAL_displaytools."""

from __future__ import annotations


def renderer_closed_loop_status_packet() -> dict[str, object]:
    return {
        "schema": "rrkal_displaytools.closed_loop_status.v1",
        "closed": [
            {
                "id": "qt_profile_launch_packet",
                "scope": ["profile templates", "profile schema", "launch packet export"],
                "evidence": ["profile_schema.py", "profiles/*.json", "scripts/export_launch_packet.py"],
            },
            {
                "id": "layer_runtime_bridge",
                "scope": ["visibility", "lock guard", "opacity", "blend", "selected renderer target"],
                "evidence": ["layer-runtime-state-file", "layer-runtime-ack-file"],
            },
            {
                "id": "selected_layer_picking_bridge",
                "scope": ["Pin", "traffic point", "boundary line", "hydrology line"],
                "evidence": ["layer-pick-state-file", "rrkal_displaytools.renderer_layer_pick_state.v1"],
            },
            {
                "id": "layer_stack_undo_snapshots",
                "scope": ["visibility", "lock", "opacity", "blend mode", "active layer"],
                "evidence": [
                    "Qt Layers Undo 圖層狀態",
                    "rrkal_displaytools.layer_stack_undo.v1",
                    "launch_packet layer_undo",
                ],
            },
            {
                "id": "session_journal_handoff",
                "scope": ["layer runtime history", "Pin pick history", "renderer ack presence", "session event portability"],
                "evidence": [
                    "launch_packet session_journal",
                    "research provenance session_journal",
                    "rrkal_displaytools.session_journal.v1",
                ],
            },
            {
                "id": "renderer_capability_discovery",
                "scope": ["renderer capabilities", "layer manifest", "profile templates"],
                "evidence": [
                    "--print-renderer-capabilities",
                    "--print-layer-manifest",
                    "rrkal_displaytools_qt_panel.py --list-templates",
                    "renderer capabilities profile_launch_readiness",
                    "renderer capabilities profile_launch_readiness_ui",
                    "renderer capabilities layer_visual_presets",
                    "renderer capabilities layer_visual_preset_runtime_feedback",
                    "renderer capabilities hydrology_lod_readiness",
                    "renderer capabilities hydrology_lod_runtime_evidence",
                    "Qt Hydro LOD JSON action",
                    "renderer capabilities ocean_material_control_port",
                    "Qt Ocean port JSON action",
                    "renderer capabilities style_renderer_entries",
                    "renderer capabilities style_profile_renderer_routes",
                    "Qt Style routes JSON action",
                    "renderer capabilities module_boundary_registry",
                    "Qt Module seams JSON action",
                    "renderer capabilities cross_machine_clone_readiness",
                    "Qt Clone ready JSON action",
                    "Qt grouped contract inspector tooltips",
                    "Qt Actions section headers",
                    "Qt Layer matrix Inspect action",
                    "Qt Pin pick JSON action",
                    "Qt Cursor geo JSON action",
                    "Qt Boundary JSON action",
                    "Qt inspector action prefix",
                    "renderer capabilities layer_operator_shortcuts",
                    "renderer capabilities layer_operator_groups",
                    "renderer capabilities layer_selection_tool",
                    "renderer capabilities layer_research_workflow",
                    "renderer capabilities boundary_emphasis_control",
                    "renderer capabilities boundary_emphasis row_double_click_binding",
                    "renderer capabilities boundary_emphasis renderer_bridge_contract",
                    "renderer capabilities cursor_geodesy_readout",
                    "renderer capabilities cursor_geodesy renderer raycast contract",
                    "renderer capabilities cursor_geodesy renderer mouse state ack bridge",
                    "renderer capabilities pin_overlay horizon occlusion",
                    "renderer capabilities pin_overlay renderer-first cursor fill priority",
                    "renderer capabilities layer_capability_matrix",
                    "renderer capabilities layer_runtime_evidence_summary",
                    "renderer capabilities layer_runtime_badge_summary",
                    "renderer capabilities layer_runtime_warning_list",
                    "renderer capabilities layer_runtime_interaction_context",
                    "renderer capabilities layer_territory_identity_context",
                    "renderer capabilities layer_authoritative_identity_source",
                    "renderer capabilities layer_renderer_diagnostics_summary",
                    "renderer capabilities layer_renderer_diagnostics_detail",
                    "renderer capabilities layer_renderer_diagnostics_remediation",
                ],
            },
            {
                "id": "diagnostics_handoff_contracts",
                "scope": [
                    "active_layer_diagnostics",
                    "boundary_highlight.identity_status",
                    "layer_undo",
                    "session_journal",
                    "timeline_state",
                    "canvas_preview stream provenance",
                ],
                "evidence": [
                    "launch_packet active_layer_diagnostics",
                    "launch_packet boundary_highlight.identity_status",
                    "launch_packet layer_filter",
                    "launch_packet layer_group_view",
                    "launch_packet profile_launch_readiness",
                    "launch_packet profile_launch_readiness_ui",
                    "launch_packet layer_visual_presets",
                    "launch_packet layer_visual_preset_runtime_feedback",
                    "launch_packet hydrology_lod_readiness",
                    "launch_packet hydrology_lod_runtime_evidence",
                    "show_hydrology_lod_status",
                    "launch_packet ocean_material_control_port",
                    "show_ocean_material_control_port",
                    "launch_packet style_renderer_entries",
                    "launch_packet style_profile_renderer_routes",
                    "show_style_renderer_routes",
                    "launch_packet module_boundary_registry",
                    "show_module_boundary_registry",
                    "launch_packet cross_machine_clone_readiness",
                    "show_cross_machine_clone_readiness",
                    "Replay/contracts: inspect portable UI/profile replay coverage JSON",
                    "Inspect: Research interaction",
                    "show_layer_capability_matrix",
                    "show_pin_pick_state",
                    "show_cursor_geodesy_state",
                    "show_boundary_state",
                    "Inspect: Profile replay",
                    "launch_packet layer_operator_shortcuts",
                    "launch_packet layer_operator_groups",
                    "launch_packet layer_selection_tool",
                    "launch_packet layer_research_workflow",
                    "launch_packet boundary_emphasis_control",
                    "launch_packet boundary_emphasis row_double_click_binding",
                    "launch_packet boundary_emphasis renderer_bridge_contract",
                    "launch_packet cursor_geodesy_readout",
                    "launch_packet cursor_geodesy renderer raycast contract",
                    "launch_packet cursor_geodesy renderer mouse state ack bridge",
                    "launch_packet pin_overlay horizon occlusion",
                    "launch_packet pin_overlay renderer-first cursor fill priority",
                    "launch_packet layer_capability_matrix",
                    "launch_packet layer_runtime_evidence",
                    "launch_packet layer_runtime_evidence_summary",
                    "launch_packet layer_runtime_badge_summary",
                    "launch_packet layer_runtime_warning_list",
                    "launch_packet layer_runtime_interaction_context",
                    "launch_packet layer_territory_identity_context",
                    "launch_packet layer_authoritative_identity_source",
                    "launch_packet layer_renderer_diagnostics_summary",
                    "launch_packet layer_renderer_diagnostics_detail",
                    "launch_packet layer_renderer_diagnostics_remediation",
                    "launch_packet layer_undo",
                    "launch_packet session_journal",
                    "launch_packet document_undo",
                    "launch_packet timeline_state",
                    "launch_packet timeline_playback_readiness",
                    "launch_packet timeline_playback_plan",
                    "launch_packet timeline_active_step_state",
                    "renderer capabilities active_layer_diagnostics",
                    "renderer capabilities layer_capability_matrix",
                    "renderer capabilities layer_runtime_evidence",
                    "renderer capabilities layer_runtime_evidence_summary",
                    "renderer capabilities layer_runtime_badge_summary",
                    "renderer capabilities layer_runtime_warning_list",
                    "renderer capabilities layer_runtime_interaction_context",
                    "renderer capabilities layer_territory_identity_context",
                    "renderer capabilities layer_authoritative_identity_source",
                    "renderer capabilities timeline_handoff",
                    "renderer capabilities ui_handoff_contracts",
                    "profile_schema optional canvas_preview",
                ],
            },
            {
                "id": "cross_machine_bootstrap_docs",
                "scope": ["clone", "venv setup", "smoke", "Qt panel launch"],
                "evidence": ["scripts/run_qt_panel.ps1", "scripts/inspect_handoff.ps1", "docs/QUICKSTART_CLONE.zh-TW.md", "README.md"],
            },
            {
                "id": "pin_boundary_ui_handoff",
                "scope": [
                    "Pin coordinate source metadata",
                    "Pin cursor fill source UI",
                    "Pin projection rotation and occlusion note",
                    "Boundary emphasis dialog feedback",
                    "Boundary emphasis target alignment",
                    "Boundary ack history handoff",
                ],
                "evidence": [
                    "pin_overlay coordinate_source_fields",
                    "pin_overlay qt_ui_affordances",
                    "Qt Pin panel Cursor Fill row",
                    "Qt Pin panel Projection note",
                    "boundary_emphasis_control dialog_feedback",
                    "boundary_emphasis_control target_alignment",
                    "Canvas Preview Boundary target line",
                    "timeline_keyframes boundary_emphasis_control",
                    "handoff inspection pin_overlay",
                    "handoff inspection boundary_emphasis_control",
                    "renderer capabilities ui_handoff_contracts",
                ],
            },
            {
                "id": "boundary_identity_warning_handoff",
                "scope": [
                    "Qt Properties identity warning badge",
                    "Canvas Preview visible Boundary warning",
                    "Canvas preview provenance warning",
                    "No-GUI launch packet warning",
                    "Handoff inspection warning output",
                    "Smoke-gated warning contract",
                ],
                "evidence": [
                    "boundaryIdentityWarningBadge",
                    "Boundary warning:",
                    "canvas_preview.boundary_identity_warning",
                    "scripts.export_launch_packet canvas_preview boundary_identity_warning",
                    "scripts/inspect_handoff.ps1 canvas_preview boundary_identity_warning",
                    "scripts/smoke.ps1 boundary warning gates",
                ],
                "boundary": "Closed warning/provenance loop only; authoritative polygon territory identity and open-line area inference remain pending backend work.",
            },
            {
                "id": "layer_workflow_hint_handoff",
                "scope": [
                    "Qt Layers workflow hint",
                    "launch packet layer_research_workflow workflow_hint",
                    "handoff inspection workflow_hint output",
                    "renderer capability workflow_hint discovery",
                    "smoke-gated row selection and Boundary emphasis wording",
                ],
                "evidence": [
                    "layerWorkflowHint",
                    "layer_research_workflow.workflow_hint",
                    "layer_research_workflow.workflow_hint_surface",
                    "scripts/inspect_handoff.ps1 layer_research_workflow workflow_hint",
                    "taichi_global_bathymetry.py layer_research_workflow workflow_hint",
                    "scripts/smoke.ps1 layer workflow hint gates",
                ],
                "boundary": "Closed UI/operator guidance loop only; renderer layer picking and backend geospatial identity refinements remain separate.",
            },
            {
                "id": "profile_ui_state_replay_handoff",
                "scope": [
                    "Qt profile UI replay label",
                    "Qt Profile replay JSON action",
                    "launch packet profile_ui_state_replay contract",
                    "renderer capability profile_ui_state_replay discovery",
                    "handoff inspection profile_ui_state_replay output",
                    "research provenance profile_ui_state_replay",
                    "smoke-gated saved state groups and replay surfaces",
                ],
                "evidence": [
                    "profileUiStateReplay",
                    "show_profile_ui_state_replay",
                    "rrkal_displaytools.profile_ui_state_replay.v1",
                    "profile_ui_state_replay.saved_state_groups",
                    "profile_ui_state_replay.replay_surfaces",
                    "scripts/inspect_handoff.ps1 profile_ui_state_replay",
                    "scripts/smoke.ps1 profile UI state replay gates",
                ],
                "boundary": "Closed profile/UI replay evidence loop only; it does not claim RRKAL data cache governance or authoritative geospatial identity resolution.",
            },
        ],
        "partial": [
            {
                "id": "boundary_highlight_mask",
                "applies": [
                    "line hover mask",
                    "outline glow",
                    "closed-ring polygon fill preview",
                    "closed-ring fill contrast/gamma",
                    "closed-ring area hit test",
                    "source-property feature identity",
                    "maritime property key identity",
                    "boundary identity-status handoff",
                    "boundary identity source hint handoff",
                    "boundary identity source hint summary",
                    "Qt Boundary identity source_hint visible summary",
                    "Qt Boundary identity warning badge",
                    "Qt Layers workflow hint",
                    "launch/handoff Layers workflow hint",
                    "renderer capability Layers workflow hint",
                    "Canvas Preview boundary identity warning provenance",
                    "No-GUI launch packet boundary identity warning",
                    "handoff inspection boundary identity warning",
                ],
                "pending": ["authoritative_polygon_territory_identity", "open_line_area_inference"],
                "identity_source_hint": "current preview identity uses source properties / maritime keys / closed rings; authoritative polygon and open-line inference remain pending",
                "open_line_area_inference_status": "pending_backend_geometry_closure",
                "identity_source_hint_summary": "preview/source-property identity only; authoritative polygon and open-line geometry closure remain pending",
                "evidence": ["boundary-highlight-json", "boundary-highlight-ack-file"],
            },
            {
                "id": "qt_renderer_preview",
                "applies": [
                    "Qt canvas state preview",
                    "runtime JSON inspectors",
                    "static renderer output thumbnail",
                    "static thumbnail auto-refresh",
                    "file-based live renderer frame stream",
                ],
                "pending": ["low-latency IPC/GPU frame stream"],
                "evidence": [
                    "Qt Canvas Preview",
                    "state/showcase/*.png",
                    "state/renderer_preview_frame.png",
                    "renderer_layer_runtime_state.json",
                    "renderer_layer_pick_state.json",
                ],
            },
            {
                "id": "qt_layer_filter",
                "applies": [
                    "Layers panel search/filter box",
                    "Hydrology/Maritime/Traffic/Aids/All focus preset buttons",
                    "Select first filtered layer action",
                    "Reveal selected layer row action",
                    "Layer group collapse/expand row controls",
                    "selected-layer group visibility diagnostics",
                    "profile layer_filter state",
                    "profile layer_group_view state",
                    "launch packet layer_filter contract",
                    "launch packet layer_group_view contract",
                    "provenance layer_filter contract",
                    "provenance layer_group_view contract",
                    "renderer capabilities ui_handoff_contracts",
                ],
                "pending": [],
                "evidence": [
                    "rrkal_displaytools.layer_filter.v1",
                    "layer_filter.available_presets",
                    "layer_filter.first_matched_layer",
                    "layer_filter.selected_layer_reveal_available",
                    "rrkal_displaytools.layer_group_view.v1",
                    "layer_group_view.selected_layer_hidden_by_group",
                    "Qt Layers panel filter status",
                ],
            },
            {
                "id": "qt_timeline_panel",
                "applies": [
                    "visible timeline dock",
                    "UI-only keyframe storage",
                    "UI-only keyframe restore",
                    "UI-only playback controls",
                    "No-GUI profile keyframe handoff",
                    "launch packet timeline_state contract",
                    "provenance timeline_state",
                    "renderer timeline ack handoff",
                    "no-GUI renderer ack endpoint",
                    "timeline playback readiness contract",
                    "timeline playback plan contract",
                    "timeline active segment contract",
                    "renderer startup first-keyframe apply contract",
                    "renderer startup first-keyframe pins/boundary apply",
                    "renderer discrete keyframe step playback",
                    "renderer ocean material keyframe interpolation",
                    "renderer PNG frame sequence animation export",
                    "renderer GIF animation export",
                    "renderer MP4 video export",
                    "renderer discrete camera keyframe apply",
                    "renderer camera keyframe interpolation",
                    "renderer layer opacity keyframe interpolation",
                    "renderer layer visibility/blend discrete hold",
                    "Boundary emphasis control keyframe preservation",
                    "Timeline keyframe list Boundary target summary",
                    "Qt/No-GUI Timeline export option controls",
                ],
                "pending": ["blend_crossfade_interpolation", "visibility_fade_interpolation"],
                "evidence": [
                    "Timeline dock controls",
                    "rrkal_displaytools.timeline_state.v1",
                    "rrkal_displaytools.timeline_runtime_state.v1",
                    "rrkal_displaytools.renderer_timeline_ack.v1",
                    "rrkal_displaytools.timeline_playback_readiness.v1",
                    "rrkal_displaytools.timeline_playback_plan.v1",
                    "rrkal_displaytools.timeline_segment_state.v1",
                    "rrkal_displaytools.timeline_active_step_state.v1",
                    "rrkal_displaytools.timeline_step_playback.v1",
                    "rrkal_displaytools.timeline_ocean_material_interpolation.v1",
                    "rrkal_displaytools.timeline_animation_export.v1",
                    "rrkal_displaytools.timeline_camera_keyframe.v1",
                    "rrkal_displaytools.timeline_camera_interpolation.v1",
                    "rrkal_displaytools.timeline_layer_opacity_interpolation.v1",
                    "rrkal_displaytools.timeline_layer_discrete_hold.v1",
                    "rrkal_displaytools.timeline_first_keyframe_apply.v1",
                    "timeline_keyframes.boundary_emphasis_control",
                    "renderer capabilities timeline_handoff",
                ],
            },
            {
                "id": "manual_document_snapshot_undo",
                "applies": [
                    "History panel Snapshot/Undo/Redo controls",
                    "manual profile-state snapshot capture",
                    "limited automatic snapshot capture",
                    "manual snapshot undo",
                    "manual snapshot redo",
                    "launch packet document_undo contract",
                    "provenance document_undo contract",
                ],
                "pending": [
                    "operation_level_history",
                    "persisted_lab_notebook",
                ],
                "evidence": [
                    "rrkal_displaytools.document_snapshot_undo.v1",
                    "document_undo.auto_capture_points",
                    "History dock controls",
                ],
            },
            {
                "id": "renderer_output_provenance",
                "applies": ["image output metadata sidecar", "RRKAL manifest reference passthrough"],
                "pending": [],
                "external_dependencies": ["RRKAL-side data manifest validation/ingest/governance"],
                "evidence": ["--output", "--rrkal-data-manifest-ref", "renderer_output_metadata.v1"],
            },
        ],
        "pending": [
            "authoritative polygon territory/EEZ identity",
            "open-line area inference",
            "low-latency IPC/GPU frame stream",
        ],
        "external_dependencies": ["RRKAL data manifest validation/ingest/governance"],
    }











