"""Shared closed-loop status contract for RRKAL_displaytools."""

from __future__ import annotations


def renderer_closed_loop_status_packet() -> dict[str, object]:
    return {
        "schema": "rrkal_displaytools.closed_loop_status.v1",
        "closed": [
            {
                "id": "qt_profile_launch_packet",
                "scope": ["profile templates", "profile schema", "launch packet export"],
                "evidence": ["profile_schema.py", "profiles/*.json", "scripts/export_launch_packet.py"],
            },
            {
                "id": "layer_runtime_bridge",
                "scope": ["visibility", "lock guard", "opacity", "blend", "selected renderer target"],
                "evidence": ["layer-runtime-state-file", "layer-runtime-ack-file"],
            },
            {
                "id": "selected_layer_picking_bridge",
                "scope": ["Pin", "traffic point", "boundary line", "hydrology line"],
                "evidence": ["layer-pick-state-file", "rrkal_displaytools.renderer_layer_pick_state.v1"],
            },
            {
                "id": "layer_stack_undo_snapshots",
                "scope": ["visibility", "lock", "opacity", "blend mode", "active layer"],
                "evidence": [
                    "Qt Layers Undo 圖層狀態",
                    "rrkal_displaytools.layer_stack_undo.v1",
                    "launch_packet layer_undo",
                ],
            },
            {
                "id": "session_journal_handoff",
                "scope": ["layer runtime history", "Pin pick history", "renderer ack presence", "session event portability"],
                "evidence": [
                    "launch_packet session_journal",
                    "research provenance session_journal",
                    "rrkal_displaytools.session_journal.v1",
                ],
            },
            {
                "id": "renderer_capability_discovery",
                "scope": ["renderer capabilities", "layer manifest", "profile templates"],
                "evidence": [
                    "--print-renderer-capabilities",
                    "--print-layer-manifest",
                    "rrkal_displaytools_qt_panel.py --list-templates",
                    "renderer capabilities layer_capability_matrix",
                    "renderer capabilities layer_runtime_evidence_summary",
                    "renderer capabilities layer_runtime_badge_summary",
                ],
            },
            {
                "id": "diagnostics_handoff_contracts",
                "scope": [
                    "active_layer_diagnostics",
                    "boundary_highlight.identity_status",
                    "layer_undo",
                    "session_journal",
                    "timeline_state",
                    "canvas_preview stream provenance",
                ],
                "evidence": [
                    "launch_packet active_layer_diagnostics",
                    "launch_packet boundary_highlight.identity_status",
                    "launch_packet layer_filter",
                    "launch_packet layer_group_view",
                    "launch_packet layer_capability_matrix",
                    "launch_packet layer_runtime_evidence",
                    "launch_packet layer_runtime_evidence_summary",
                    "launch_packet layer_runtime_badge_summary",
                    "launch_packet layer_undo",
                    "launch_packet session_journal",
                    "launch_packet document_undo",
                    "launch_packet timeline_state",
                    "launch_packet timeline_playback_readiness",
                    "launch_packet timeline_playback_plan",
                    "launch_packet timeline_active_step_state",
                    "renderer capabilities active_layer_diagnostics",
                    "renderer capabilities layer_capability_matrix",
                    "renderer capabilities layer_runtime_evidence",
                    "renderer capabilities layer_runtime_evidence_summary",
                    "renderer capabilities layer_runtime_badge_summary",
                    "renderer capabilities timeline_handoff",
                    "renderer capabilities ui_handoff_contracts",
                    "profile_schema optional canvas_preview",
                ],
            },
            {
                "id": "cross_machine_bootstrap_docs",
                "scope": ["clone", "venv setup", "smoke", "Qt panel launch"],
                "evidence": ["scripts/run_qt_panel.ps1", "scripts/inspect_handoff.ps1", "docs/QUICKSTART_CLONE.zh-TW.md", "README.md"],
            },
        ],
        "partial": [
            {
                "id": "boundary_highlight_mask",
                "applies": [
                    "line hover mask",
                    "outline glow",
                    "closed-ring polygon fill preview",
                    "closed-ring fill contrast/gamma",
                    "closed-ring area hit test",
                    "source-property feature identity",
                    "maritime property key identity",
                    "boundary identity-status handoff",
                ],
                "pending": ["authoritative_polygon_territory_identity", "open_line_area_inference"],
                "evidence": ["boundary-highlight-json", "boundary-highlight-ack-file"],
            },
            {
                "id": "qt_renderer_preview",
                "applies": [
                    "Qt canvas state preview",
                    "runtime JSON inspectors",
                    "static renderer output thumbnail",
                    "static thumbnail auto-refresh",
                    "file-based live renderer frame stream",
                ],
                "pending": ["low-latency IPC/GPU frame stream"],
                "evidence": [
                    "Qt Canvas Preview",
                    "state/showcase/*.png",
                    "state/renderer_preview_frame.png",
                    "renderer_layer_runtime_state.json",
                    "renderer_layer_pick_state.json",
                ],
            },
            {
                "id": "qt_layer_filter",
                "applies": [
                    "Layers panel search/filter box",
                    "Hydrology/Maritime/Traffic/Aids/All focus preset buttons",
                    "Select first filtered layer action",
                    "Reveal selected layer row action",
                    "Layer group collapse/expand row controls",
                    "selected-layer group visibility diagnostics",
                    "profile layer_filter state",
                    "profile layer_group_view state",
                    "launch packet layer_filter contract",
                    "launch packet layer_group_view contract",
                    "provenance layer_filter contract",
                    "provenance layer_group_view contract",
                    "renderer capabilities ui_handoff_contracts",
                ],
                "pending": [],
                "evidence": [
                    "rrkal_displaytools.layer_filter.v1",
                    "layer_filter.available_presets",
                    "layer_filter.first_matched_layer",
                    "layer_filter.selected_layer_reveal_available",
                    "rrkal_displaytools.layer_group_view.v1",
                    "layer_group_view.selected_layer_hidden_by_group",
                    "Qt Layers panel filter status",
                ],
            },
            {
                "id": "qt_timeline_panel",
                "applies": [
                    "visible timeline dock",
                    "UI-only keyframe storage",
                    "UI-only keyframe restore",
                    "UI-only playback controls",
                    "No-GUI profile keyframe handoff",
                    "launch packet timeline_state contract",
                    "provenance timeline_state",
                    "renderer timeline ack handoff",
                    "no-GUI renderer ack endpoint",
                    "timeline playback readiness contract",
                    "timeline playback plan contract",
                    "timeline active segment contract",
                    "renderer startup first-keyframe apply contract",
                    "renderer startup first-keyframe pins/boundary apply",
                    "renderer discrete keyframe step playback",
                    "renderer ocean material keyframe interpolation",
                    "renderer PNG frame sequence animation export",
                    "renderer GIF animation export",
                    "renderer MP4 video export",
                    "renderer discrete camera keyframe apply",
                    "renderer camera keyframe interpolation",
                    "renderer layer opacity keyframe interpolation",
                    "renderer layer visibility/blend discrete hold",
                    "Qt/No-GUI Timeline export option controls",
                ],
                "pending": ["blend_crossfade_interpolation", "visibility_fade_interpolation"],
                "evidence": [
                    "Timeline dock controls",
                    "rrkal_displaytools.timeline_state.v1",
                    "rrkal_displaytools.timeline_runtime_state.v1",
                    "rrkal_displaytools.renderer_timeline_ack.v1",
                    "rrkal_displaytools.timeline_playback_readiness.v1",
                    "rrkal_displaytools.timeline_playback_plan.v1",
                    "rrkal_displaytools.timeline_segment_state.v1",
                    "rrkal_displaytools.timeline_active_step_state.v1",
                    "rrkal_displaytools.timeline_step_playback.v1",
                    "rrkal_displaytools.timeline_ocean_material_interpolation.v1",
                    "rrkal_displaytools.timeline_animation_export.v1",
                    "rrkal_displaytools.timeline_camera_keyframe.v1",
                    "rrkal_displaytools.timeline_camera_interpolation.v1",
                    "rrkal_displaytools.timeline_layer_opacity_interpolation.v1",
                    "rrkal_displaytools.timeline_layer_discrete_hold.v1",
                    "rrkal_displaytools.timeline_first_keyframe_apply.v1",
                    "renderer capabilities timeline_handoff",
                ],
            },
            {
                "id": "manual_document_snapshot_undo",
                "applies": [
                    "History panel Snapshot/Undo/Redo controls",
                    "manual profile-state snapshot capture",
                    "limited automatic snapshot capture",
                    "manual snapshot undo",
                    "manual snapshot redo",
                    "launch packet document_undo contract",
                    "provenance document_undo contract",
                ],
                "pending": [
                    "operation_level_history",
                    "persisted_lab_notebook",
                ],
                "evidence": [
                    "rrkal_displaytools.document_snapshot_undo.v1",
                    "document_undo.auto_capture_points",
                    "History dock controls",
                ],
            },
            {
                "id": "renderer_output_provenance",
                "applies": ["image output metadata sidecar", "RRKAL manifest reference passthrough"],
                "pending": [],
                "external_dependencies": ["RRKAL-side data manifest validation/ingest/governance"],
                "evidence": ["--output", "--rrkal-data-manifest-ref", "renderer_output_metadata.v1"],
            },
        ],
        "pending": [
            "authoritative polygon territory/EEZ identity",
            "open-line area inference",
            "low-latency IPC/GPU frame stream",
        ],
        "external_dependencies": ["RRKAL data manifest validation/ingest/governance"],
    }
