"""Render-core helpers extracted from the Taichi globe prototype."""

from .render_plan import (
    alpha_blend_compose,
    alpha_compose,
    alpha_compose_transparent,
    build_compiled_layer_render_plan_packet,
    build_layer_render_plan_adapter_boundary_contract,
    build_layer_render_plan_adapter_payload_summary,
    build_layer_render_plan_bottleneck_recommendation,
    build_layer_render_plan_apply_path,
    build_layer_render_plan_batch_decisions,
    build_layer_render_plan_composition_steps,
    build_layer_render_plan_compose_queue_entries,
    build_layer_render_plan_compose_queue_packet,
    build_layer_render_plan_cache_invalidation_reasons,
    build_layer_render_plan_cache_invalidation_scope,
    build_layer_render_plan_cache_key,
    build_layer_render_plan_compose_run_parity_contract,
    build_layer_render_plan_compose_runs,
    build_layer_render_plan_execution_summary,
    build_layer_render_plan_execution_phases,
    build_layer_render_plan_metadata_summary,
    build_layer_render_plan_phase_timing_contract,
    build_layer_render_plan_phase_timing_runtime_packet,
    build_layer_render_plan_runtime_snapshot,
    build_layer_render_plan_single_pass_preflight_contract,
    build_reused_compiled_layer_render_plan_packet,
)

__all__ = [
    "alpha_blend_compose",
    "alpha_compose",
    "alpha_compose_transparent",
    "build_compiled_layer_render_plan_packet",
    "build_layer_render_plan_adapter_boundary_contract",
    "build_layer_render_plan_adapter_payload_summary",
    "build_layer_render_plan_bottleneck_recommendation",
    "build_layer_render_plan_apply_path",
    "build_layer_render_plan_batch_decisions",
    "build_layer_render_plan_composition_steps",
    "build_layer_render_plan_compose_queue_entries",
    "build_layer_render_plan_compose_queue_packet",
    "build_layer_render_plan_cache_invalidation_reasons",
    "build_layer_render_plan_cache_invalidation_scope",
    "build_layer_render_plan_cache_key",
    "build_layer_render_plan_compose_run_parity_contract",
    "build_layer_render_plan_compose_runs",
    "build_layer_render_plan_execution_summary",
    "build_layer_render_plan_execution_phases",
    "build_layer_render_plan_metadata_summary",
    "build_layer_render_plan_phase_timing_contract",
    "build_layer_render_plan_phase_timing_runtime_packet",
    "build_layer_render_plan_runtime_snapshot",
    "build_layer_render_plan_single_pass_preflight_contract",
    "build_reused_compiled_layer_render_plan_packet",
]
