"""Shared layer render-plan performance handoff contract."""

from __future__ import annotations


def layer_render_plan_performance_packet(
    source: str,
    layer_capability_matrix: dict[str, object] | None = None,
    module_boundaries: dict[str, object] | None = None,
) -> dict[str, object]:
    matrix = layer_capability_matrix if isinstance(layer_capability_matrix, dict) else {}
    modules = module_boundaries if isinstance(module_boundaries, dict) else {}
    live_counts = matrix.get("live_counts") if isinstance(matrix.get("live_counts"), dict) else {}
    stage_order = [
        "collect_qt_layer_state",
        "resolve_renderer_targets_and_aliases",
        "compile_visibility_opacity_blend_pick_state",
        "freeze_static_geometry_batches",
        "apply_dirty_flags",
        "submit_single_taichi_render_pass",
    ]
    return {
        "schema": "rrkal_displaytools.layer_render_plan_performance.v1",
        "source": source,
        "status": "queued_after_module_decoupling",
        "post_decoupling_priority": 1,
        "optimization_target": "precompute_layer_state_then_single_render_pass",
        "current_runtime_claim": "contract_and_schedule_only",
        "runtime_optimization_applied": False,
        "runtime_snapshot_schema": "rrkal_displaytools.layer_render_plan_runtime_snapshot.v1",
        "runtime_snapshot_helper": "HybridRenderController.layer_render_plan_runtime_snapshot",
        "composition_steps_helper": "render_core.render_plan.build_layer_render_plan_composition_steps",
        "composition_steps_input_collector": "HybridRenderController.layer_render_plan_composition_steps",
        "composition_apply_helper": "HybridRenderController.apply_layer_render_plan_composition",
        "compiled_plan_schema": "rrkal_displaytools.compiled_layer_render_plan.v1",
        "compiled_plan_helper": "HybridRenderController.compile_layer_render_plan",
        "compiled_plan_cache_key_helper": "render_core.render_plan.build_layer_render_plan_cache_key",
        "compiled_plan_cache_status_field": "cache_status",
        "compiled_plan_adapter_payload_schema": "rrkal_displaytools.layer_render_plan_adapter_payload.v1",
        "compiled_plan_adapter_payload_helper": "build_layer_render_plan_adapter_payload",
        "compiled_plan_adapter_payload_field": "adapter_payload",
        "compiled_plan_adapter_payload_summary_schema": "rrkal_displaytools.layer_render_plan_adapter_payload_summary.v1",
        "compiled_plan_adapter_payload_summary_field": "adapter_payload_summary",
        "compiled_plan_adapter_payload_status_field": "adapter_payload_status",
        "compiled_plan_adapter_payload_contract_schema": "rrkal_displaytools.layer_render_plan_adapter_payload_contract.v1",
        "compiled_plan_adapter_payload_contract_field": "adapter_payload_contract",
        "compiled_plan_adapter_payload_contract_status_field": "adapter_payload_contract_status",
        "compiled_plan_adapter_payload_primary_gate": "do_not_make_payload_primary_implementation_until_status_ready",
        "compiled_plan_invalidation_reason_schema": "rrkal_displaytools.layer_render_plan_cache_invalidation_reasons.v1",
        "compiled_plan_invalidation_helper": "render_core.render_plan.build_layer_render_plan_cache_invalidation_reasons",
        "compiled_plan_invalidation_reasons_field": "cache_invalidation_reasons",
        "compiled_plan_invalidation_scope_schema": "rrkal_displaytools.layer_render_plan_cache_invalidation_scope.v1",
        "compiled_plan_invalidation_scope_helper": "render_core.render_plan.build_layer_render_plan_cache_invalidation_scope",
        "compiled_plan_invalidation_scope_field": "cache_invalidation_scope",
        "compiled_plan_batch_decision_schema": "rrkal_displaytools.layer_render_plan_batch_decisions.v1",
        "compiled_plan_batch_decision_helper": "render_core.render_plan.build_layer_render_plan_batch_decisions",
        "compiled_plan_batch_decision_field": "batch_decisions",
        "compiled_plan_apply_path_schema": "rrkal_displaytools.layer_render_plan_apply_path.v1",
        "compiled_plan_apply_path_helper": "render_core.render_plan.build_layer_render_plan_apply_path",
        "compiled_plan_apply_path_field": "apply_path",
        "compiled_plan_execution_summary_schema": "rrkal_displaytools.layer_render_plan_execution_summary.v1",
        "compiled_plan_execution_summary_helper": "render_core.render_plan.build_layer_render_plan_execution_summary",
        "compiled_plan_execution_summary_field": "execution_summary",
        "compiled_plan_execution_phases_schema": "rrkal_displaytools.layer_render_plan_execution_phases.v1",
        "compiled_plan_execution_phases_helper": "render_core.render_plan.build_layer_render_plan_execution_phases",
        "compiled_plan_execution_phases_field": "execution_phases",
        "compiled_plan_phase_timing_contract_schema": "rrkal_displaytools.layer_render_plan_phase_timing_contract.v1",
        "compiled_plan_phase_timing_contract_helper": "render_core.render_plan.build_layer_render_plan_phase_timing_contract",
        "compiled_plan_phase_timing_contract_field": "phase_timing_contract",
        "compiled_plan_phase_timing_runtime_schema": "rrkal_displaytools.layer_render_plan_phase_timing_runtime.v1",
        "compiled_plan_phase_timing_runtime_helper": "render_core.render_plan.build_layer_render_plan_phase_timing_runtime_packet",
        "compiled_plan_phase_timing_runtime_field": "phase_timing_runtime",
        "compiled_plan_bottleneck_recommendation_schema": "rrkal_displaytools.layer_render_plan_bottleneck_recommendation.v1",
        "compiled_plan_bottleneck_recommendation_helper": "render_core.render_plan.build_layer_render_plan_bottleneck_recommendation",
        "compiled_plan_bottleneck_recommendation_field": "bottleneck_recommendation",
        "compiled_plan_compose_queue_schema": "rrkal_displaytools.layer_render_plan_compose_queue.v1",
        "compiled_plan_compose_queue_helper": "HybridRenderController.layer_render_plan_compose_queue",
        "compiled_plan_compose_queue_field": "compose_queue",
        "compiled_plan_compose_queue_skip_reasons": ["hidden_layer", "missing_overlay", "transparent_overlay"],
        "compiled_plan_compose_runs_schema": "rrkal_displaytools.layer_render_plan_compose_runs.v1",
        "compiled_plan_compose_runs_helper": "render_core.render_plan.build_layer_render_plan_compose_runs",
            "compiled_plan_compose_runs_field": "compose_runs",
            "compiled_plan_compose_run_parity_contract_schema": "rrkal_displaytools.layer_render_plan_compose_run_parity_contract.v1",
            "compiled_plan_compose_run_parity_contract_helper": "render_core.render_plan.build_layer_render_plan_compose_run_parity_contract",
            "compiled_plan_compose_run_parity_contract_field": "compose_run_parity_contract",
            "compose_run_parity_smoke_schema": "rrkal_displaytools.render_compose_parity_smoke.v1",
            "compose_run_parity_smoke_script": "scripts\\render_compose_parity_smoke.ps1",
            "compose_run_parity_smoke_manifest": "state/render_compose_parity_smoke_manifest.json",
            "compose_run_parity_smoke_precommit_required": False,
            "compose_run_parity_smoke_precommit_command": "powershell -NoProfile -ExecutionPolicy Bypass -File scripts\\render_compose_parity_smoke.ps1 -ContractOnly",
            "compose_run_parity_smoke_validates": ["png_dimensions_match", "max_abs_diff", "changed_pixel_count"],
            "compose_run_parity_smoke_pass_fields": ["passed", "precommit_gate_passed", "visual_parity_passed", "max_abs_diff", "changed_pixel_count", "diff_status", "notification_level"],
            "compose_pass_budget_schema": "rrkal_displaytools.layer_render_plan_compose_pass_budget.v1",
            "compose_pass_budget": {
                "schema": "rrkal_displaytools.layer_render_plan_compose_pass_budget.v1",
                "status": "planning_ready_runtime_merge_blocked",
                "current_pass_model": "sequential_overlay_composition",
                "target_pass_model": "collapsed_overlay_runs_then_single_taichi_composite_pass",
                "first_safe_optimization": "collapse_adjacent_alpha_compose_runs_after_zero_diff_parity",
                "compose_run_count_field": "compose_run_count",
                "merge_candidate_run_count_field": "compose_merge_candidate_run_count",
                "required_evidence": [
                    "render_compose_parity_smoke.visual_parity_passed",
                    "max_abs_diff=0",
                    "changed_pixel_count=0",
                ],
                "ui_summary_format": "Compose budget: runs={compose_run_count}; merge_candidates={compose_merge_candidate_run_count}; evidence=compose_parity_runner; runtime_merge=false",
                "qt_label_object": "composePassBudgetStrip",
                "qt_refresh": "refresh_layer_render_plan_cache_diagnostics_strip",
                "runtime_diagnostic_fields": [
                    "cache_diagnostics.phase_timing_ms.compose_overlays",
                    "cache_diagnostics.slowest_phase_id",
                    "cache_diagnostics.slow_frame_threshold_ms",
                ],
                "bottleneck_advice_rules": {
                    "compose_overlays": "run_parity_then_collapse_runs",
                    "prepare_batches": "inspect_static_batch_cache_reuse",
                    "postprocess": "inspect_style_fold_or_defer",
                    "unknown": "await_runtime_metadata",
                },
                "advice_field": "compose_bottleneck_advice",
                "runtime_merge_enabled": False,
                "boundary": "Budget metadata only; renderer keeps the existing sequential compose path until parity evidence proves the collapsed path.",
            },
            "compose_run_merge_preflight_schema": "rrkal_displaytools.compose_run_merge_preflight.v1",
        "compose_run_merge_preflight": {
            "schema": "rrkal_displaytools.compose_run_merge_preflight.v1",
            "status": "blocked_until_zero_diff_parity_artifacts",
            "runtime_merge_enabled": False,
            "target_optimization": "collapse_adjacent_alpha_compose_runs",
            "required_evidence": [
                "compose_run_parity_artifact_workflow.runner_manifest",
                "state/compose_parity/baseline_sequential_frame_rgba.png",
                "state/compose_parity/merged_candidate_frame_rgba.png",
                "render_compose_parity_smoke.visual_parity_passed",
            ],
            "preflight_checks": [
                "runner_available",
                "baseline_artifact_exists",
                "candidate_artifact_exists",
                "png_dimensions_match",
                "max_abs_diff_zero",
                "changed_pixel_count_zero",
            ],
            "failure_policy": "keep_sequential_compose_queue",
            "success_next_step": "enable_manual_collapsed_run_candidate_behind_flag",
            "qt_summary_field": "composePassBudgetStrip",
            "reviewer_field": "layer_render_plan_performance.compose_run_merge_preflight",
        },
        "compose_run_merge_preflight_summary_contract_schema": "rrkal_displaytools.compose_run_merge_preflight_summary_contract.v1",
        "compose_run_merge_preflight_summary_contract": {
            "schema": "rrkal_displaytools.compose_run_merge_preflight_summary_contract.v1",
            "summary_format": "Compose merge preflight: status={status}; runtime_merge={runtime_merge_enabled}; required={required_evidence}; next={success_next_step}",
            "qt_copy_action": "copy_compose_pass_budget_summary",
            "launch_packet_field": "layer_render_plan_performance.compose_run_merge_preflight",
            "renderer_capability_field": "layer_render_plan_performance.compose_run_merge_preflight",
            "handoff_field": "layer_render_plan_performance.compose_run_merge_preflight",
            "portable": True,
        },        "compose_pass_budget_summary_contract_schema": "rrkal_displaytools.layer_render_plan_compose_pass_budget_summary_contract.v1",

            "compose_pass_budget_summary_contract": {
                "schema": "rrkal_displaytools.layer_render_plan_compose_pass_budget_summary_contract.v1",
                "summary_format": "Compose budget: status={status}; runs={compose_run_count}; merge={compose_merge_candidate_run_count}; compose_ms={compose_ms}; slowest={slowest_phase_id}; advice={compose_bottleneck_advice}; target={target_pass_model}; runtime_merge=false",
                "qt_copy_action": "copy_compose_pass_budget_summary",
                "qt_action_label": "Copy compose budget",
                "qt_label_object": "composePassBudgetStrip",
                "portable": True,
                "boundary": "Copyable performance handoff summary only; it does not enable runtime compose merging.",
            },
            "compose_run_parity_artifact_runner_schema": "rrkal_displaytools.compose_run_parity_artifact_runner.v1",
            "compose_run_parity_artifact_runner_script": "scripts\\render_compose_parity_artifacts.ps1",
            "compose_run_parity_artifact_workflow_schema": "rrkal_displaytools.compose_run_parity_artifact_workflow.v1",
            "compose_run_parity_artifact_workflow": {
                "schema": "rrkal_displaytools.compose_run_parity_artifact_workflow.v1",
                "status": "producer_ready_runtime_merge_disabled",
                "renderer_arg": "--compose-parity-artifact-dir",
                "artifact_dir": "state/compose_parity",
                "baseline_artifact": "state/compose_parity/baseline_sequential_frame_rgba.png",
                "candidate_artifact": "state/compose_parity/merged_candidate_frame_rgba.png",
                "metadata_artifact": "state/compose_parity/renderer_output_metadata.json",
                "diff_script": "scripts\\render_compose_parity_smoke.ps1",
                "precommit_command": "powershell -NoProfile -ExecutionPolicy Bypass -File scripts\\render_compose_parity_smoke.ps1 -ContractOnly",
                "manual_diff_command": "powershell -NoProfile -ExecutionPolicy Bypass -File scripts\\render_compose_parity_smoke.ps1",
                "producer_command": "py -3 taichi_global_bathymetry.py --once --output state/compose_parity/renderer_frame.png --compose-parity-artifact-dir state/compose_parity",
                "runner_script": "scripts\\render_compose_parity_artifacts.ps1",
                "runner_command": "powershell -NoProfile -ExecutionPolicy Bypass -File scripts\\render_compose_parity_artifacts.ps1",
                "runner_manifest": "state/compose_parity/compose_parity_artifact_runner.json",
                "producer_status": "baseline_and_candidate_artifact_producer_available_runtime_merge_disabled",
                "candidate_schema": "rrkal_displaytools.compose_run_parity_candidate.v1",
                "artifacts_schema": "rrkal_displaytools.compose_run_parity_artifacts.v1",
                "next_step": "Run the manual diff command on generated artifacts and require zero-diff evidence before enabling runtime merge.",
                "boundary": "Workflow metadata only; runtime artifacts stay under state/ and are not committed.",
            },
            "compose_run_parity_summary_contract_schema": "rrkal_displaytools.compose_run_parity_summary_contract.v1",
            "compose_run_parity_summary_contract": {
                "schema": "rrkal_displaytools.compose_run_parity_summary_contract.v1",
                "summary_format": "Compose parity: status={status}; producer={producer_status}; dir={artifact_dir}; baseline={baseline_artifact}; candidate={candidate_artifact}; produce={producer_command}; run={runner_command}; diff={manual_diff_command}; precommit={precommit_command}; runtime_merge=false",
                "summary_parameter_fields": [
                    "status",
                    "producer_status",
                    "artifact_dir",
                    "baseline_artifact",
                    "candidate_artifact",
                    "producer_command",
                    "runner_command",
                    "manual_diff_command",
                    "precommit_command",
                ],
                "qt_copy_action": "copy_compose_parity_workflow_summary",
                "qt_action_label": "Copy compose parity",
                "portable": True,
                "boundary": "Copyable command summary only; runtime artifacts remain local under state/compose_parity.",
            },
            "phase_timing_unit": "milliseconds",
            "compiled_plan_reuse_decision_field": "cache_reuse_decision",
            "compiled_plan_reuse_policy": "reuse_when_cache_key_matches_previous_compiled_plan",
        "compiled_plan_reuse_status_values": ["compiled", "reused"],
        "compiled_plan_reuse_boundary_field": "reuse_boundary",
        "compiled_plan_reuse_boundary": "valid_until_dirty_flags_or_camera_change",
        "compiled_plan_reuse_runtime_fields": ["cache_key", "cache_status", "reuse_policy", "reuse_boundary", "frame_index", "dirty_flags"],
        "cache_diagnostics_schema": "rrkal_displaytools.layer_render_plan_cache_diagnostics.v1",
        "cache_diagnostics_qt_action": "show_layer_render_plan_performance",
        "cache_diagnostics_metadata_source": "renderer_output_metadata.layer_render_plan",
        "cache_diagnostics_control_board_schema": "rrkal_displaytools.layer_render_plan_cache_control_board.v1",
        "cache_diagnostics_control_board_label_object": "renderPlanCacheDiagnosticsStrip",
        "cache_diagnostics_control_board_button_object": "renderPlanCacheDiagnosticsButton",
        "cache_diagnostics_control_board_default_visible": True,
        "metadata_sidecar_field": "layer_render_plan",
        "runtime_snapshot_wired": True,
        "deferred_until": "module_decoupling_boundary_contract_is_stable",
        "module_boundary_schema": modules.get("schema"),
        "stage_order": stage_order,
        "precompute_inputs": [
            "profile.layers",
            "layer_stack_ui",
            "layer_capability_matrix",
            "boundary_highlight",
            "pins",
            "ocean_material_control_port",
            "timeline_state",
        ],
        "dirty_flags": [
            "camera",
            "style_profile",
            "ocean_material",
            "layer_visibility",
            "layer_opacity",
            "layer_blend",
            "timeline_step",
            "data_manifest_ref",
        ],
        "batching_targets": [
            "hydrology_polylines",
            "boundary_and_maritime_lines",
            "pin_markers",
            "traffic_points",
            "scale_grid_contours",
        ],
        "single_pass_outputs": ["globe_frame", "overlay_composite", "metadata_sidecar"],
        "known_risk": "Independent layer render paths can make Taichi interaction feel sluggish when overlays grow.",
        "performance_strategy": "Compile renderer-ready layer state once per dirty change, then let Taichi consume a unified render plan in one render/composite path.",
        "live_control_counts": live_counts,
        "requires_modules": [
            "contracts/launch_packets.py",
            "render_core/taichi_globe.py",
            "overlays/vector_layers.py",
            "diagnostics/handoff.py",
        ],
        "launch_packet_fields": ["layer_render_plan_performance", "layer_capability_matrix", "module_boundary_registry"],
        "renderer_capability_field": "layer_render_plan_performance",
        "handoff_field": "layer_render_plan_performance",
        "smoke_gate": "layer_render_plan_performance",
        "boundary": "This records the next renderer performance closure after module decoupling; it does not claim a measured FPS or rewritten Taichi render loop yet.",
    }
